# Generated by Django 5.1.2 on 2024-11-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=15)),
                ('month_files', models.IntegerField()),
                ('max_files', models.IntegerField()),
                ('load', models.CharField(max_length=10)),
                ('scarcity', models.IntegerField()),
            ],
        ),
    ]
