# Generated by Django 5.1.2 on 2024-11-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculateddata',
            name='month_files',
        ),
    ]
