# Generated by Django 5.1.2 on 2024-11-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0002_remove_calculateddata_month_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=30)),
                ('month_files', models.IntegerField()),
                ('avg_fact_files_per_month', models.IntegerField()),
                ('cnt_machines', models.IntegerField()),
                ('max_files', models.IntegerField()),
                ('load_fact', models.CharField(max_length=10)),
                ('scarcity_fact', models.IntegerField()),
                ('cnt_UZ', models.IntegerField()),
                ('load_plan', models.CharField(max_length=10)),
                ('scarcity_plan', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CalculatedData',
        ),
    ]
