# Generated by Django 5.1.2 on 2024-11-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0004_data_machine_type1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='machine_type1',
        ),
    ]
