# Generated by Django 5.1.2 on 2024-11-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0005_remove_data_machine_type1'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='avg_fact_files_with_new',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
