# Generated by Django 5.1.2 on 2024-11-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0006_data_avg_fact_files_with_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='new_users_files',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
