# Generated by Django 5.1.2 on 2024-11-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0007_data_new_users_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='machine_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
