# Generated by Django 5.1.2 on 2024-11-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0008_data_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='permitted_load',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
