# Generated by Django 5.1.2 on 2024-11-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0010_facttablecolumnname_plantablecolumnname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facttablecolumnname',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='facttablecolumnname',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='plantablecolumnname',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='plantablecolumnname',
            name='machine_type',
        ),
    ]
