# Generated by Django 5.1.2 on 2024-11-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0011_remove_facttablecolumnname_machine_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableColumnName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_files', models.CharField(max_length=40)),
                ('avg_fact_files_per_month', models.CharField(max_length=40)),
                ('avg_fact_files_with_new', models.CharField(max_length=40)),
                ('new_users_files', models.CharField(max_length=40)),
                ('cnt_machines', models.CharField(max_length=40)),
                ('max_files', models.CharField(max_length=40)),
                ('load_fact', models.CharField(max_length=40)),
                ('scarcity_fact', models.CharField(max_length=40)),
                ('cnt_UZ', models.CharField(max_length=40)),
                ('load_plan', models.CharField(max_length=40)),
                ('scarcity_plan', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='FactTableColumnName',
        ),
        migrations.DeleteModel(
            name='PlanTableColumnName',
        ),
    ]
