# Generated by Django 5.1.2 on 2024-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorFactPlan', '0012_tablecolumnname_delete_facttablecolumnname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPasswordChangeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('last_password_change_date', models.DateField()),
            ],
        ),
    ]
